# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sigmoid": "data.ipynb",
         "make_bimodal_assymetric_regression": "data.ipynb",
         "make_confounded_data": "data.ipynb",
         "get_distribution_var_factor_jaccard": "dist.ipynb",
         "pointwise_variance": "dist.ipynb",
         "estimate_mean_and_variance_from_neighbors_mixture": "dist.ipynb",
         "sample_from_neighbors_continuous": "dist.ipynb",
         "PointwiseMixture": "dist.ipynb",
         "JaccardPointwiseGaussianMixture": "dist.ipynb",
         "pandas_gorupby_apply_parallel": "estimators.ipynb",
         "idxs_split": "estimators.ipynb",
         "SMFormulaWrapper": "estimators.ipynb",
         "SMWrapper": "estimators.ipynb",
         "CEDTEstimator": "estimators.ipynb",
         "parallel_apply": "utils.ipynb",
         "get_default_args": "utils.ipynb",
         "inherit_docstrings": "utils.ipynb",
         "make_batches": "utils.ipynb",
         "sim_matrix_to_idx_and_score": "utils.ipynb",
         "cosine_similarity": "utils.ipynb",
         "cosine_distance": "utils.ipynb",
         "similarity_plot": "utils.ipynb",
         "sparsify": "utils.ipynb",
         "hstack": "utils.ipynb",
         "vstack": "utils.ipynb",
         "stack": "utils.ipynb",
         "RobustEncoder": "utils.ipynb"}

modules = ["data.py",
           "dist.py",
           "estimators.py",
           "utils.py"]

doc_url = "https://AlanGanem.github.io/fkausality/fkausality/"

git_url = "https://github.com/AlanGanem/fkausality/tree/master/"

def custom_doc_links(name): return None
