# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_distribution_var_factor_jaccard": "dist.ipynb",
         "pointwise_variance": "dist.ipynb",
         "estimate_mean_and_variance_from_neighbors": "dist.ipynb",
         "sample_from_neighbors_continuous": "dist.ipynb",
         "PointwiseGaussianMixture": "dist.ipynb",
         "SMFormulaWrapper": "estimators.ipynb",
         "SMWrapper": "estimators.ipynb",
         "EstimatorKernel": "kernel.ipynb",
         "JaccardForestKernel": "kernel.ipynb",
         "CategoricalLinearKernel": "kernel.ipynb",
         "ClassificationLinearBottleneck": "kernel.ipynb",
         "RegressionLinearBottleneck": "kernel.ipynb",
         "MLPKernel": "kernel.ipynb",
         "BOWKernel": "kernel.ipynb",
         "NMSLibSklearnWrapper": "neighbors.ipynb",
         "FastJaccardNN": "neighbors.ipynb",
         "FastL2NN": "neighbors.ipynb",
         "FastKLDivNN": "neighbors.ipynb",
         "get_default_args": "utils.ipynb",
         "inherit_docstrings": "utils.ipynb",
         "make_batches": "utils.ipynb",
         "sim_matrix_to_idx_and_score": "utils.ipynb",
         "cosine_similarity": "utils.ipynb",
         "cosine_distance": "utils.ipynb",
         "similarity_plot": "utils.ipynb",
         "sparsify": "utils.ipynb",
         "hstack": "utils.ipynb",
         "vstack": "utils.ipynb",
         "stack": "utils.ipynb",
         "RobustEncoder": "utils.ipynb"}

modules = ["dist.py",
           "estimators.py",
           "kernel.py",
           "neighbors.py",
           "utils.py"]

doc_url = "https://AlanGanem.github.io/fkausality/fkausality/"

git_url = "https://github.com/AlanGanem/fkausality/tree/master/"

def custom_doc_links(name): return None
